/*
 * This file is generated by jOOQ.
*/
package brs.schema.tables.records;


import brs.schema.tables.Purchase;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseRecord extends UpdatableRecordImpl<PurchaseRecord> implements Record22<Long, Long, Long, Long, Long, Integer, Long, Integer, byte[], byte[], Integer, Boolean, byte[], byte[], byte[], byte[], Boolean, Boolean, Long, Long, Integer, Boolean> {

    private static final long serialVersionUID = -942129552;

    /**
     * Setter for <code>DB.purchase.db_id</code>.
     */
    public void setDbId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DB.purchase.db_id</code>.
     */
    public Long getDbId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DB.purchase.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DB.purchase.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DB.purchase.buyer_id</code>.
     */
    public void setBuyerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>DB.purchase.buyer_id</code>.
     */
    public Long getBuyerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>DB.purchase.goods_id</code>.
     */
    public void setGoodsId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>DB.purchase.goods_id</code>.
     */
    public Long getGoodsId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>DB.purchase.seller_id</code>.
     */
    public void setSellerId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>DB.purchase.seller_id</code>.
     */
    public Long getSellerId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>DB.purchase.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>DB.purchase.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>DB.purchase.price</code>.
     */
    public void setPrice(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>DB.purchase.price</code>.
     */
    public Long getPrice() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>DB.purchase.deadline</code>.
     */
    public void setDeadline(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>DB.purchase.deadline</code>.
     */
    public Integer getDeadline() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>DB.purchase.note</code>.
     */
    public void setNote(byte... value) {
        set(8, value);
    }

    /**
     * Getter for <code>DB.purchase.note</code>.
     */
    public byte[] getNote() {
        return (byte[]) get(8);
    }

    /**
     * Setter for <code>DB.purchase.nonce</code>.
     */
    public void setNonce(byte... value) {
        set(9, value);
    }

    /**
     * Getter for <code>DB.purchase.nonce</code>.
     */
    public byte[] getNonce() {
        return (byte[]) get(9);
    }

    /**
     * Setter for <code>DB.purchase.timestamp</code>.
     */
    public void setTimestamp(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>DB.purchase.timestamp</code>.
     */
    public Integer getTimestamp() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>DB.purchase.pending</code>.
     */
    public void setPending(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>DB.purchase.pending</code>.
     */
    public Boolean getPending() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>DB.purchase.goods</code>.
     */
    public void setGoods(byte... value) {
        set(12, value);
    }

    /**
     * Getter for <code>DB.purchase.goods</code>.
     */
    public byte[] getGoods() {
        return (byte[]) get(12);
    }

    /**
     * Setter for <code>DB.purchase.goods_nonce</code>.
     */
    public void setGoodsNonce(byte... value) {
        set(13, value);
    }

    /**
     * Getter for <code>DB.purchase.goods_nonce</code>.
     */
    public byte[] getGoodsNonce() {
        return (byte[]) get(13);
    }

    /**
     * Setter for <code>DB.purchase.refund_note</code>.
     */
    public void setRefundNote(byte... value) {
        set(14, value);
    }

    /**
     * Getter for <code>DB.purchase.refund_note</code>.
     */
    public byte[] getRefundNote() {
        return (byte[]) get(14);
    }

    /**
     * Setter for <code>DB.purchase.refund_nonce</code>.
     */
    public void setRefundNonce(byte... value) {
        set(15, value);
    }

    /**
     * Getter for <code>DB.purchase.refund_nonce</code>.
     */
    public byte[] getRefundNonce() {
        return (byte[]) get(15);
    }

    /**
     * Setter for <code>DB.purchase.has_feedback_notes</code>.
     */
    public void setHasFeedbackNotes(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>DB.purchase.has_feedback_notes</code>.
     */
    public Boolean getHasFeedbackNotes() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>DB.purchase.has_public_feedbacks</code>.
     */
    public void setHasPublicFeedbacks(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>DB.purchase.has_public_feedbacks</code>.
     */
    public Boolean getHasPublicFeedbacks() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>DB.purchase.discount</code>.
     */
    public void setDiscount(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>DB.purchase.discount</code>.
     */
    public Long getDiscount() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>DB.purchase.refund</code>.
     */
    public void setRefund(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>DB.purchase.refund</code>.
     */
    public Long getRefund() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>DB.purchase.height</code>.
     */
    public void setHeight(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>DB.purchase.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>DB.purchase.latest</code>.
     */
    public void setLatest(Boolean value) {
        set(21, value);
    }

    /**
     * Getter for <code>DB.purchase.latest</code>.
     */
    public Boolean getLatest() {
        return (Boolean) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Long, Long, Long, Long, Long, Integer, Long, Integer, byte[], byte[], Integer, Boolean, byte[], byte[], byte[], byte[], Boolean, Boolean, Long, Long, Integer, Boolean> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Long, Long, Long, Long, Long, Integer, Long, Integer, byte[], byte[], Integer, Boolean, byte[], byte[], byte[], byte[], Boolean, Boolean, Long, Long, Integer, Boolean> valuesRow() {
        return (Row22) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Purchase.PURCHASE.DB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Purchase.PURCHASE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Purchase.PURCHASE.BUYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Purchase.PURCHASE.GOODS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Purchase.PURCHASE.SELLER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Purchase.PURCHASE.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Purchase.PURCHASE.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Purchase.PURCHASE.DEADLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field9() {
        return Purchase.PURCHASE.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field10() {
        return Purchase.PURCHASE.NONCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Purchase.PURCHASE.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return Purchase.PURCHASE.PENDING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field13() {
        return Purchase.PURCHASE.GOODS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field14() {
        return Purchase.PURCHASE.GOODS_NONCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field15() {
        return Purchase.PURCHASE.REFUND_NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field16() {
        return Purchase.PURCHASE.REFUND_NONCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field17() {
        return Purchase.PURCHASE.HAS_FEEDBACK_NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field18() {
        return Purchase.PURCHASE.HAS_PUBLIC_FEEDBACKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field19() {
        return Purchase.PURCHASE.DISCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field20() {
        return Purchase.PURCHASE.REFUND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field21() {
        return Purchase.PURCHASE.HEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field22() {
        return Purchase.PURCHASE.LATEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getDbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getBuyerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getSellerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component9() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component10() {
        return getNonce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getPending();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component13() {
        return getGoods();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component14() {
        return getGoodsNonce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component15() {
        return getRefundNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component16() {
        return getRefundNonce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component17() {
        return getHasFeedbackNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component18() {
        return getHasPublicFeedbacks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component19() {
        return getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component20() {
        return getRefund();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component21() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component22() {
        return getLatest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getDbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getBuyerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getSellerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value9() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value10() {
        return getNonce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getPending();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value13() {
        return getGoods();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value14() {
        return getGoodsNonce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value15() {
        return getRefundNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value16() {
        return getRefundNonce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value17() {
        return getHasFeedbackNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value18() {
        return getHasPublicFeedbacks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value19() {
        return getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value20() {
        return getRefund();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value21() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value22() {
        return getLatest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value1(Long value) {
        setDbId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value2(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value3(Long value) {
        setBuyerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value4(Long value) {
        setGoodsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value5(Long value) {
        setSellerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value6(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value7(Long value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value8(Integer value) {
        setDeadline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value9(byte... value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value10(byte... value) {
        setNonce(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value11(Integer value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value12(Boolean value) {
        setPending(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value13(byte... value) {
        setGoods(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value14(byte... value) {
        setGoodsNonce(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value15(byte... value) {
        setRefundNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value16(byte... value) {
        setRefundNonce(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value17(Boolean value) {
        setHasFeedbackNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value18(Boolean value) {
        setHasPublicFeedbacks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value19(Long value) {
        setDiscount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value20(Long value) {
        setRefund(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value21(Integer value) {
        setHeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord value22(Boolean value) {
        setLatest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Integer value6, Long value7, Integer value8, byte[] value9, byte[] value10, Integer value11, Boolean value12, byte[] value13, byte[] value14, byte[] value15, byte[] value16, Boolean value17, Boolean value18, Long value19, Long value20, Integer value21, Boolean value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaseRecord
     */
    public PurchaseRecord() {
        super(Purchase.PURCHASE);
    }

    /**
     * Create a detached, initialised PurchaseRecord
     */
    public PurchaseRecord(Long dbId, Long id, Long buyerId, Long goodsId, Long sellerId, Integer quantity, Long price, Integer deadline, byte[] note, byte[] nonce, Integer timestamp, Boolean pending, byte[] goods, byte[] goodsNonce, byte[] refundNote, byte[] refundNonce, Boolean hasFeedbackNotes, Boolean hasPublicFeedbacks, Long discount, Long refund, Integer height, Boolean latest) {
        super(Purchase.PURCHASE);

        set(0, dbId);
        set(1, id);
        set(2, buyerId);
        set(3, goodsId);
        set(4, sellerId);
        set(5, quantity);
        set(6, price);
        set(7, deadline);
        set(8, note);
        set(9, nonce);
        set(10, timestamp);
        set(11, pending);
        set(12, goods);
        set(13, goodsNonce);
        set(14, refundNote);
        set(15, refundNonce);
        set(16, hasFeedbackNotes);
        set(17, hasPublicFeedbacks);
        set(18, discount);
        set(19, refund);
        set(20, height);
        set(21, latest);
    }
}
