/*
 * This file is generated by jOOQ.
*/
package brs.schema.tables.records;


import brs.schema.tables.PurchaseFeedback;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseFeedbackRecord extends UpdatableRecordImpl<PurchaseFeedbackRecord> implements Record6<Long, Long, byte[], byte[], Integer, Boolean> {

    private static final long serialVersionUID = -439571790;

    /**
     * Setter for <code>DB.purchase_feedback.db_id</code>.
     */
    public void setDbId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DB.purchase_feedback.db_id</code>.
     */
    public Long getDbId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DB.purchase_feedback.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DB.purchase_feedback.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DB.purchase_feedback.feedback_data</code>.
     */
    public void setFeedbackData(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>DB.purchase_feedback.feedback_data</code>.
     */
    public byte[] getFeedbackData() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>DB.purchase_feedback.feedback_nonce</code>.
     */
    public void setFeedbackNonce(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>DB.purchase_feedback.feedback_nonce</code>.
     */
    public byte[] getFeedbackNonce() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>DB.purchase_feedback.height</code>.
     */
    public void setHeight(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>DB.purchase_feedback.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>DB.purchase_feedback.latest</code>.
     */
    public void setLatest(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>DB.purchase_feedback.latest</code>.
     */
    public Boolean getLatest() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, byte[], byte[], Integer, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, byte[], byte[], Integer, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PurchaseFeedback.PURCHASE_FEEDBACK.DB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PurchaseFeedback.PURCHASE_FEEDBACK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return PurchaseFeedback.PURCHASE_FEEDBACK.FEEDBACK_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return PurchaseFeedback.PURCHASE_FEEDBACK.FEEDBACK_NONCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return PurchaseFeedback.PURCHASE_FEEDBACK.HEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return PurchaseFeedback.PURCHASE_FEEDBACK.LATEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getDbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component3() {
        return getFeedbackData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component4() {
        return getFeedbackNonce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getLatest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getDbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getFeedbackData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getFeedbackNonce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getLatest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseFeedbackRecord value1(Long value) {
        setDbId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseFeedbackRecord value2(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseFeedbackRecord value3(byte... value) {
        setFeedbackData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseFeedbackRecord value4(byte... value) {
        setFeedbackNonce(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseFeedbackRecord value5(Integer value) {
        setHeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseFeedbackRecord value6(Boolean value) {
        setLatest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PurchaseFeedbackRecord values(Long value1, Long value2, byte[] value3, byte[] value4, Integer value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaseFeedbackRecord
     */
    public PurchaseFeedbackRecord() {
        super(PurchaseFeedback.PURCHASE_FEEDBACK);
    }

    /**
     * Create a detached, initialised PurchaseFeedbackRecord
     */
    public PurchaseFeedbackRecord(Long dbId, Long id, byte[] feedbackData, byte[] feedbackNonce, Integer height, Boolean latest) {
        super(PurchaseFeedback.PURCHASE_FEEDBACK);

        set(0, dbId);
        set(1, id);
        set(2, feedbackData);
        set(3, feedbackNonce);
        set(4, height);
        set(5, latest);
    }
}
