/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Nov 21 20:51:45 GMT 2017
 */

package brs.crypto;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Crypto_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "brs.crypto.Crypto"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "Europe/Berlin"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Crypto_ESTest_scaffolding.class.getClassLoader() ,
      "brs.crypto.ReedSolomon$CodewordInvalidException",
      "org.bouncycastle.util.Arrays",
      "org.bouncycastle.crypto.params.ParametersWithIV",
      "brs.crypto.ReedSolomon",
      "org.bouncycastle.crypto.CryptoException",
      "org.bouncycastle.crypto.modes.CBCBlockCipher",
      "org.bouncycastle.crypto.engines.AESEngine",
      "org.bouncycastle.crypto.InvalidCipherTextException",
      "org.bouncycastle.crypto.paddings.BlockCipherPadding",
      "org.bouncycastle.crypto.DataLengthException",
      "brs.crypto.ReedSolomon$CodewordTooLongException",
      "brs.crypto.ReedSolomon$DecodeException",
      "brs.crypto.Curve25519",
      "org.bouncycastle.crypto.params.ParametersWithRandom",
      "org.bouncycastle.util.Pack",
      "brs.crypto.Crypto",
      "org.bouncycastle.crypto.params.KeyParameter",
      "org.bouncycastle.crypto.CipherParameters",
      "org.bouncycastle.crypto.OutputLengthException",
      "org.bouncycastle.crypto.BufferedBlockCipher",
      "org.bouncycastle.crypto.BlockCipher",
      "brs.BurstException$ValidationException",
      "brs.BurstException$NotValidException",
      "brs.crypto.Curve25519$long10",
      "org.bouncycastle.crypto.paddings.PKCS7Padding",
      "brs.BurstException",
      "org.bouncycastle.crypto.paddings.PaddedBufferedBlockCipher",
      "brs.util.Convert",
      "brs.crypto.Crypto$1",
      "org.bouncycastle.crypto.RuntimeCryptoException"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Crypto_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "brs.crypto.Crypto",
      "brs.crypto.Curve25519",
      "brs.util.Convert",
      "brs.crypto.ReedSolomon",
      "brs.crypto.ReedSolomon$DecodeException",
      "brs.crypto.ReedSolomon$CodewordTooLongException",
      "brs.crypto.ReedSolomon$CodewordInvalidException",
      "org.bouncycastle.crypto.CryptoException",
      "org.bouncycastle.crypto.InvalidCipherTextException",
      "org.bouncycastle.crypto.engines.AESEngine",
      "org.bouncycastle.crypto.RuntimeCryptoException",
      "org.bouncycastle.crypto.DataLengthException",
      "org.bouncycastle.crypto.OutputLengthException"
    );
  }
}
