/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 21 21:27:45 GMT 2017
 */

package brs.at;

import org.junit.Test;
import static org.junit.Assert.*;
import brs.at.AT_Exception;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AT_Exception_ESTest extends AT_Exception_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AT_Exception aT_Exception0 = new AT_Exception("");
  }
}
