/*
 * This file is generated by jOOQ.
*/
package brs.schema.tables;


import brs.schema.Db;
import brs.schema.Indexes;
import brs.schema.Keys;
import brs.schema.tables.records.EscrowRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Escrow extends TableImpl<EscrowRecord> {

    private static final long serialVersionUID = -567114920;

    /**
     * The reference instance of <code>DB.escrow</code>
     */
    public static final Escrow ESCROW = new Escrow();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EscrowRecord> getRecordType() {
        return EscrowRecord.class;
    }

    /**
     * The column <code>DB.escrow.db_id</code>.
     */
    public final TableField<EscrowRecord, Long> DB_ID = createField("db_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>DB.escrow.id</code>.
     */
    public final TableField<EscrowRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.escrow.sender_id</code>.
     */
    public final TableField<EscrowRecord, Long> SENDER_ID = createField("sender_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.escrow.recipient_id</code>.
     */
    public final TableField<EscrowRecord, Long> RECIPIENT_ID = createField("recipient_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.escrow.amount</code>.
     */
    public final TableField<EscrowRecord, Long> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.escrow.required_signers</code>.
     */
    public final TableField<EscrowRecord, Integer> REQUIRED_SIGNERS = createField("required_signers", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>DB.escrow.deadline</code>.
     */
    public final TableField<EscrowRecord, Integer> DEADLINE = createField("deadline", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.escrow.deadline_action</code>.
     */
    public final TableField<EscrowRecord, Integer> DEADLINE_ACTION = createField("deadline_action", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.escrow.height</code>.
     */
    public final TableField<EscrowRecord, Integer> HEIGHT = createField("height", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.escrow.latest</code>.
     */
    public final TableField<EscrowRecord, Boolean> LATEST = createField("latest", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>DB.escrow</code> table reference
     */
    public Escrow() {
        this(DSL.name("escrow"), null);
    }

    /**
     * Create an aliased <code>DB.escrow</code> table reference
     */
    public Escrow(String alias) {
        this(DSL.name(alias), ESCROW);
    }

    /**
     * Create an aliased <code>DB.escrow</code> table reference
     */
    public Escrow(Name alias) {
        this(alias, ESCROW);
    }

    private Escrow(Name alias, Table<EscrowRecord> aliased) {
        this(alias, aliased, null);
    }

    private Escrow(Name alias, Table<EscrowRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Db.DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ESCROW_ESCROW_DEADLINE_HEIGHT_IDX, Indexes.ESCROW_ESCROW_ID_HEIGHT_IDX, Indexes.ESCROW_ESCROW_RECIPIENT_ID_HEIGHT_IDX, Indexes.ESCROW_ESCROW_SENDER_ID_HEIGHT_IDX, Indexes.ESCROW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EscrowRecord, Long> getIdentity() {
        return Keys.IDENTITY_ESCROW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EscrowRecord> getPrimaryKey() {
        return Keys.KEY_ESCROW_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EscrowRecord>> getKeys() {
        return Arrays.<UniqueKey<EscrowRecord>>asList(Keys.KEY_ESCROW_PRIMARY, Keys.KEY_ESCROW_ESCROW_ID_HEIGHT_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Escrow as(String alias) {
        return new Escrow(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Escrow as(Name alias) {
        return new Escrow(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Escrow rename(String name) {
        return new Escrow(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Escrow rename(Name name) {
        return new Escrow(name, null);
    }
}
