/*
 * This file is generated by jOOQ.
*/
package brs.schema.tables;


import brs.schema.Db;
import brs.schema.Indexes;
import brs.schema.Keys;
import brs.schema.tables.records.UnconfirmedTransactionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnconfirmedTransaction extends TableImpl<UnconfirmedTransactionRecord> {

    private static final long serialVersionUID = 1205910340;

    /**
     * The reference instance of <code>DB.unconfirmed_transaction</code>
     */
    public static final UnconfirmedTransaction UNCONFIRMED_TRANSACTION = new UnconfirmedTransaction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UnconfirmedTransactionRecord> getRecordType() {
        return UnconfirmedTransactionRecord.class;
    }

    /**
     * The column <code>DB.unconfirmed_transaction.db_id</code>.
     */
    public final TableField<UnconfirmedTransactionRecord, Long> DB_ID = createField("db_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>DB.unconfirmed_transaction.id</code>.
     */
    public final TableField<UnconfirmedTransactionRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.unconfirmed_transaction.expiration</code>.
     */
    public final TableField<UnconfirmedTransactionRecord, Integer> EXPIRATION = createField("expiration", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.unconfirmed_transaction.transaction_height</code>.
     */
    public final TableField<UnconfirmedTransactionRecord, Integer> TRANSACTION_HEIGHT = createField("transaction_height", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.unconfirmed_transaction.fee_per_byte</code>.
     */
    public final TableField<UnconfirmedTransactionRecord, Long> FEE_PER_BYTE = createField("fee_per_byte", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.unconfirmed_transaction.timestamp</code>.
     */
    public final TableField<UnconfirmedTransactionRecord, Integer> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.unconfirmed_transaction.transaction_bytes</code>.
     */
    public final TableField<UnconfirmedTransactionRecord, byte[]> TRANSACTION_BYTES = createField("transaction_bytes", org.jooq.impl.SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>DB.unconfirmed_transaction.height</code>.
     */
    public final TableField<UnconfirmedTransactionRecord, Integer> HEIGHT = createField("height", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>DB.unconfirmed_transaction</code> table reference
     */
    public UnconfirmedTransaction() {
        this(DSL.name("unconfirmed_transaction"), null);
    }

    /**
     * Create an aliased <code>DB.unconfirmed_transaction</code> table reference
     */
    public UnconfirmedTransaction(String alias) {
        this(DSL.name(alias), UNCONFIRMED_TRANSACTION);
    }

    /**
     * Create an aliased <code>DB.unconfirmed_transaction</code> table reference
     */
    public UnconfirmedTransaction(Name alias) {
        this(alias, UNCONFIRMED_TRANSACTION);
    }

    private UnconfirmedTransaction(Name alias, Table<UnconfirmedTransactionRecord> aliased) {
        this(alias, aliased, null);
    }

    private UnconfirmedTransaction(Name alias, Table<UnconfirmedTransactionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Db.DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.UNCONFIRMED_TRANSACTION_PRIMARY, Indexes.UNCONFIRMED_TRANSACTION_UNCONFIRMED_TRANSACTION_HEIGHT_FEE_TIMESTAMP_IDX, Indexes.UNCONFIRMED_TRANSACTION_UNCONFIRMED_TRANSACTION_ID_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UnconfirmedTransactionRecord, Long> getIdentity() {
        return Keys.IDENTITY_UNCONFIRMED_TRANSACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UnconfirmedTransactionRecord> getPrimaryKey() {
        return Keys.KEY_UNCONFIRMED_TRANSACTION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UnconfirmedTransactionRecord>> getKeys() {
        return Arrays.<UniqueKey<UnconfirmedTransactionRecord>>asList(Keys.KEY_UNCONFIRMED_TRANSACTION_PRIMARY, Keys.KEY_UNCONFIRMED_TRANSACTION_UNCONFIRMED_TRANSACTION_ID_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnconfirmedTransaction as(String alias) {
        return new UnconfirmedTransaction(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnconfirmedTransaction as(Name alias) {
        return new UnconfirmedTransaction(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UnconfirmedTransaction rename(String name) {
        return new UnconfirmedTransaction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UnconfirmedTransaction rename(Name name) {
        return new UnconfirmedTransaction(name, null);
    }
}
