/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 21 21:01:53 GMT 2017
 */

package brs.crypto.hash;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import brs.crypto.hash.DigestEngine;
import brs.crypto.hash.RIPEMD;
import brs.crypto.hash.RIPEMD160;
import brs.crypto.hash.SHA256;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DigestEngine_ESTest extends DigestEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      byte[] byteArray0 = rIPEMD0.digest();
      rIPEMD0.update(byteArray0, (-4597), (-151));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SHA256 sHA256_0 = new SHA256();
      RIPEMD rIPEMD0 = new RIPEMD();
      byte[] byteArray0 = sHA256_0.getBlockBuffer();
      rIPEMD0.processBlock(byteArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      rIPEMD0.engineReset();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      RIPEMD160 rIPEMD160_0 = new RIPEMD160();
      rIPEMD160_0.doInit();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      rIPEMD0.getInternalBlockLength();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      RIPEMD160 rIPEMD160_0 = new RIPEMD160();
      rIPEMD160_0.getBlockCount();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      RIPEMD160 rIPEMD160_0 = new RIPEMD160();
      rIPEMD160_0.flush();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      byte[] byteArray0 = new byte[4];
      rIPEMD0.digest(byteArray0, (int) (byte)1, (int) (byte)0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      byte[] byteArray0 = new byte[2];
      rIPEMD0.digest(byteArray0, (int) (byte)0, (int) (byte)1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      RIPEMD160 rIPEMD160_0 = new RIPEMD160();
      rIPEMD160_0.copyState(rIPEMD160_0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      byte[] byteArray0 = new byte[4];
      // Undeclared exception!
      try { 
        rIPEMD0.update(byteArray0, (-4034), (int) (byte)58);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SHA256 sHA256_0 = new SHA256();
      // Undeclared exception!
      try { 
        sHA256_0.update((byte[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brs.crypto.hash.DigestEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      RIPEMD160 rIPEMD160_0 = new RIPEMD160();
      // Undeclared exception!
      try { 
        rIPEMD160_0.processBlock((byte[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brs.crypto.hash.RIPEMD160", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      RIPEMD160 rIPEMD160_0 = new RIPEMD160();
      byte[] byteArray0 = new byte[8];
      // Undeclared exception!
      try { 
        rIPEMD160_0.processBlock(byteArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 8
         //
         verifyException("brs.crypto.hash.RIPEMD160", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      RIPEMD160 rIPEMD160_0 = new RIPEMD160();
      // Undeclared exception!
      try { 
        rIPEMD160_0.doPadding((byte[]) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brs.crypto.hash.RIPEMD160", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SHA256 sHA256_0 = new SHA256();
      byte[] byteArray0 = new byte[1];
      // Undeclared exception!
      try { 
        sHA256_0.doPadding(byteArray0, 7388);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 7388
         //
         verifyException("brs.crypto.hash.SHA2Core", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      RIPEMD160 rIPEMD160_0 = new RIPEMD160();
      // Undeclared exception!
      try { 
        rIPEMD160_0.digest((byte[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brs.crypto.hash.DigestEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      RIPEMD160 rIPEMD160_0 = new RIPEMD160();
      // Undeclared exception!
      try { 
        rIPEMD160_0.copyState((DigestEngine) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brs.crypto.hash.DigestEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SHA256 sHA256_0 = new SHA256();
      RIPEMD rIPEMD0 = new RIPEMD();
      // Undeclared exception!
      try { 
        sHA256_0.copyState(rIPEMD0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      RIPEMD160 rIPEMD160_0 = new RIPEMD160();
      byte[] byteArray0 = new byte[7];
      rIPEMD160_0.update(byteArray0, (int) (byte)1, (int) (byte)1);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      // Undeclared exception!
      try { 
        rIPEMD0.update((byte[]) null, 3061, 3061);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      rIPEMD0.update((byte) (-1));
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      rIPEMD0.reset();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      byte[] byteArray0 = new byte[1];
      rIPEMD0.update(byteArray0);
      rIPEMD0.flush();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      byte[] byteArray0 = new byte[9];
      // Undeclared exception!
      try { 
        rIPEMD0.digest(byteArray0, (int) (byte)0, (int) (byte) (-97));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      RIPEMD160 rIPEMD160_0 = new RIPEMD160();
      rIPEMD160_0.copy();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      byte[] byteArray0 = rIPEMD0.getBlockBuffer();
      rIPEMD0.doPadding(byteArray0, 39);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      RIPEMD rIPEMD0 = new RIPEMD();
      byte[] byteArray0 = new byte[8];
      rIPEMD0.digest(byteArray0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SHA256 sHA256_0 = new SHA256();
      // Undeclared exception!
      try { 
        sHA256_0.digest((byte[]) null, 65, 65);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brs.crypto.hash.SHA2Core", e);
      }
  }
}
