/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 21 21:36:14 GMT 2017
 */

package brs.crypto.hash;

import org.junit.Test;
import static org.junit.Assert.*;
import brs.crypto.hash.Digest;
import brs.crypto.hash.SHA256;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SHA256_ESTest extends SHA256_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SHA256 sHA256_0 = new SHA256();
      sHA256_0.getInitVal();
      assertEquals(32, sHA256_0.getDigestLength());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SHA256 sHA256_0 = new SHA256();
      int int0 = sHA256_0.getDigestLength();
      assertEquals(32, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SHA256 sHA256_0 = new SHA256();
      Digest digest0 = sHA256_0.copy();
      assertEquals(32, digest0.getDigestLength());
  }
}
