/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 21 20:34:36 GMT 2017
 */

package brs;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import brs.BlockImpl;
import brs.TransactionImpl;
import java.math.BigInteger;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BlockImpl_ESTest extends BlockImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JSONObject jSONObject0 = new JSONObject();
      JSONObject jSONObject1 = new JSONObject(jSONObject0);
      Object object0 = new Object();
      jSONObject1.put(jSONObject0, object0);
      jSONObject0.put(object0, jSONObject1);
      // Undeclared exception!
      BlockImpl.parseBlock(jSONObject1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JSONObject jSONObject0 = new JSONObject();
      JSONArray jSONArray0 = new JSONArray();
      jSONArray0.add((Object) jSONObject0);
      Object object0 = new Object();
      jSONObject0.put(jSONArray0, object0);
      // Undeclared exception!
      try { 
        BlockImpl.parseBlock(jSONObject0);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        BlockImpl.parseBlock((JSONObject) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brs.BlockImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JSONObject jSONObject0 = new JSONObject();
      // Undeclared exception!
      try { 
        BlockImpl.parseBlock(jSONObject0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("brs.BlockImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      LinkedList<TransactionImpl> linkedList0 = new LinkedList<TransactionImpl>();
      BlockImpl blockImpl0 = null;
      try {
        blockImpl0 = new BlockImpl((-2089), 716, 716, (-2089), (-1819L), 3712, byteArray0, (byte[]) null, (byte[]) null, (byte[]) null, byteArray0, linkedList0, (-2089), byteArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class brs.Burst
         //
         verifyException("brs.BlockImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      byte[] byteArray0 = new byte[19];
      BigInteger bigInteger0 = new BigInteger(byteArray0);
      Long long0 = new Long(1991);
      BlockImpl blockImpl0 = null;
      try {
        blockImpl0 = new BlockImpl(1991, 1991, 1991, (-1573L), (-1573L), 1991, byteArray0, byteArray0, byteArray0, byteArray0, byteArray0, bigInteger0, 1991, 1991, 1991, long0, (-1573L), byteArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class brs.Burst
         //
         verifyException("brs.BlockImpl", e);
      }
  }
}
