/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Nov 21 20:33:19 GMT 2017
 */

package brs;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TransactionType_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "brs.TransactionType"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.timezone", "Europe/Berlin"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TransactionType_ESTest_scaffolding.class.getClassLoader() ,
      "brs.Attachment",
      "brs.Attachment$AdvancedPaymentSubscriptionSubscribe",
      "org.bouncycastle.asn1.ASN1Sequence",
      "brs.Attachment$DigitalGoodsDelisting",
      "brs.Attachment$AbstractAttachment",
      "brs.TransactionType$ColoredCoins$ColoredCoinsOrderCancellation",
      "com.codahale.metrics.MetricRegistry$MetricBuilder",
      "brs.Attachment$DigitalGoodsPriceChange",
      "com.codahale.metrics.MetricSet",
      "brs.TransactionType$Fee",
      "com.codahale.metrics.Reservoir",
      "brs.Attachment$AdvancedPaymentEscrowResult",
      "brs.db.EntityTable",
      "brs.Generator",
      "brs.TransactionType$DigitalGoods",
      "brs.Generator$GeneratorState",
      "org.bouncycastle.asn1.BERSequence",
      "brs.BlockchainProcessor$TransactionNotAcceptedException",
      "brs.Appendix$EncryptToSelfMessage",
      "brs.TransactionType$Payment",
      "brs.db.store.Dbs",
      "org.bouncycastle.asn1.ASN1TaggedObject",
      "brs.Attachment$BurstMiningRewardRecipientAssignment",
      "brs.Attachment$DigitalGoodsPurchase",
      "com.codahale.metrics.Metric",
      "brs.Attachment$MessagingAliasBuy",
      "brs.Attachment$DigitalGoodsQuantityChange",
      "brs.TransactionType$ColoredCoins",
      "brs.Attachment$AccountControlEffectiveBalanceLeasing",
      "brs.db.store.Stores",
      "brs.TransactionType$Payment$1",
      "org.bouncycastle.asn1.ASN1GeneralizedTime",
      "org.bouncycastle.asn1.DLOutputStream",
      "org.bouncycastle.asn1.DERPrintableString",
      "brs.BurstException",
      "brs.at.AT_Exception",
      "org.bouncycastle.asn1.OIDTokenizer",
      "org.bouncycastle.asn1.x509.X509ObjectIdentifiers",
      "brs.util.Time$EpochTime",
      "org.bouncycastle.asn1.ASN1Primitive",
      "brs.db.VersionedEntityTable",
      "org.bouncycastle.util.Arrays",
      "brs.TransactionType$BurstMining$1",
      "brs.util.Listener",
      "brs.Burst",
      "brs.TransactionType$AdvancedPayment$1",
      "brs.TransactionType$AutomatedTransactions$1",
      "brs.TransactionType$AdvancedPayment$2",
      "brs.TransactionType$AdvancedPayment$3",
      "brs.TransactionType$AdvancedPayment$4",
      "brs.TransactionType$AutomatedTransactions$2",
      "brs.TransactionType$AdvancedPayment",
      "brs.TransactionType$AdvancedPayment$5",
      "brs.Appendix$AbstractEncryptedMessage",
      "brs.TransactionProcessor",
      "brs.TransactionType$AdvancedPayment$6",
      "brs.Attachment$MessagingAccountInfo",
      "brs.Order",
      "org.bouncycastle.asn1.DERTaggedObject",
      "brs.TransactionType$ColoredCoins$4",
      "brs.TransactionType$ColoredCoins$3",
      "brs.util.Observable",
      "brs.db.BurstIterator",
      "brs.BlockchainProcessor$BlockOutOfOrderException",
      "brs.TransactionType$ColoredCoins$2",
      "brs.TransactionType$ColoredCoins$1",
      "brs.Attachment$EmptyAttachment",
      "brs.TransactionType$ColoredCoins$6",
      "brs.TransactionType$ColoredCoins$5",
      "brs.BlockchainProcessor",
      "brs.Constants",
      "org.bouncycastle.asn1.DERUTF8String",
      "org.bouncycastle.asn1.ASN1OutputStream",
      "com.codahale.metrics.MetricRegistry",
      "org.bouncycastle.asn1.x509.X509Name",
      "org.bouncycastle.asn1.x509.X509NameEntryConverter",
      "org.bouncycastle.asn1.DLSequence",
      "brs.db.DerivedTable",
      "brs.BurstException$NotYetEnabledException",
      "brs.Order$Bid",
      "brs.Attachment$DigitalGoodsListing",
      "brs.Attachment$ColoredCoinsOrderCancellation",
      "brs.Appendix$PublicKeyAnnouncement",
      "org.bouncycastle.asn1.ASN1OutputStream$ImplicitOutputStream",
      "brs.util.ThreadPool",
      "brs.TransactionType$DigitalGoods$7",
      "brs.TransactionType$DigitalGoods$8",
      "brs.TransactionType$DigitalGoods$5",
      "brs.BlockchainProcessor$BlockNotAcceptedException",
      "brs.TransactionType$DigitalGoods$6",
      "brs.TransactionType$AccountControl$1",
      "brs.TransactionType$DigitalGoods$3",
      "brs.GeneratorImpl$1",
      "brs.TransactionType$DigitalGoods$4",
      "org.bouncycastle.asn1.ASN1String",
      "brs.TransactionType$DigitalGoods$1",
      "brs.Attachment$ColoredCoinsBidOrderPlacement",
      "brs.TransactionType$DigitalGoods$2",
      "brs.util.Convert",
      "org.bouncycastle.asn1.DEROutputStream",
      "com.codahale.metrics.MetricRegistry$MetricBuilder$2",
      "com.codahale.metrics.MetricRegistry$MetricBuilder$1",
      "brs.BlockImpl",
      "brs.Attachment$MessagingAliasSell",
      "org.bouncycastle.asn1.ASN1TaggedObjectParser",
      "brs.peer.Peer",
      "com.codahale.metrics.MetricRegistry$MetricBuilder$4",
      "org.bouncycastle.asn1.ASN1SequenceParser",
      "org.bouncycastle.asn1.ASN1Exception",
      "com.codahale.metrics.MetricRegistry$MetricBuilder$3",
      "brs.TransactionType$Messaging",
      "brs.crypto.EncryptedData$1",
      "brs.BurstException$NotCurrentlyValidException",
      "org.bouncycastle.asn1.ASN1ObjectIdentifier$OidHandle",
      "brs.Attachment$ColoredCoinsAssetTransfer",
      "org.bouncycastle.asn1.DERGeneralizedTime",
      "org.bouncycastle.asn1.ASN1Object",
      "org.bouncycastle.asn1.ASN1ObjectIdentifier",
      "brs.Attachment$ColoredCoinsAssetIssuance",
      "brs.util.Time",
      "brs.Attachment$ColoredCoinsBidOrderCancellation",
      "brs.Attachment$ColoredCoinsAskOrderCancellation",
      "org.bouncycastle.asn1.DERSequence",
      "brs.Appendix$EncryptedMessage",
      "org.bouncycastle.asn1.DLTaggedObject",
      "brs.BurstException$NotValidException",
      "org.json.simple.JSONObject",
      "brs.Attachment$AdvancedPaymentEscrowSign",
      "brs.TransactionType$ColoredCoins$ColoredCoinsOrderPlacement",
      "org.bouncycastle.asn1.x509.X509DefaultEntryConverter",
      "brs.TransactionImpl",
      "brs.Attachment$MessagingPollCreation",
      "brs.Attachment$ColoredCoinsOrderPlacement",
      "brs.Appendix",
      "brs.TransactionType",
      "brs.Account",
      "org.bouncycastle.util.Encodable",
      "brs.Generator$Event",
      "org.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers",
      "brs.Attachment$DigitalGoodsFeedback",
      "brs.Blockchain",
      "brs.db.BurstKey",
      "brs.Account$RewardRecipientAssignment",
      "org.json.simple.JSONStreamAware",
      "org.json.simple.JSONAware",
      "brs.Attachment$MessagingAliasAssignment",
      "brs.TransactionType$AccountControl",
      "brs.Attachment$DigitalGoodsDelivery",
      "brs.TransactionType$Messaging$6",
      "brs.Appendix$Message",
      "org.bouncycastle.asn1.InMemoryRepresentable",
      "brs.TransactionType$Messaging$5",
      "brs.TransactionType$Messaging$4",
      "brs.Block",
      "brs.TransactionType$Messaging$3",
      "brs.util.Listeners",
      "brs.TransactionType$Messaging$2",
      "brs.TransactionType$Messaging$1",
      "org.bouncycastle.util.Iterable",
      "org.bouncycastle.asn1.DERIA5String",
      "brs.Account$DoubleSpendingException",
      "org.bouncycastle.asn1.ASN1Encodable",
      "brs.TransactionType$AutomatedTransactions",
      "brs.Appendix$AbstractAppendix",
      "brs.Attachment$AdvancedPaymentSubscriptionPayment",
      "brs.Attachment$MessagingVoteCasting",
      "brs.util.ThreadPool$2",
      "brs.util.ThreadPool$1",
      "brs.TransactionType$BurstMining",
      "brs.TransactionType$Messaging$7",
      "brs.Transaction",
      "brs.Attachment$AdvancedPaymentEscrowCreation",
      "brs.Attachment$DigitalGoodsRefund",
      "brs.Attachment$AdvancedPaymentSubscriptionCancel",
      "brs.GeneratorImpl",
      "brs.Account$Event",
      "brs.BurstException$ValidationException",
      "brs.Order$Ask",
      "brs.crypto.EncryptedData",
      "brs.Attachment$ColoredCoinsAskOrderPlacement",
      "brs.Attachment$1",
      "brs.Attachment$3",
      "brs.Attachment$AutomatedTransactionsCreation",
      "brs.Attachment$2"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TransactionType_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "brs.TransactionType",
      "brs.TransactionType$AutomatedTransactions",
      "brs.TransactionType$AdvancedPayment",
      "brs.TransactionType$BurstMining",
      "brs.TransactionType$AccountControl",
      "brs.TransactionType$DigitalGoods",
      "brs.TransactionType$ColoredCoins",
      "brs.TransactionType$Messaging",
      "brs.TransactionType$Payment",
      "brs.util.ThreadPool",
      "brs.GeneratorImpl",
      "brs.Burst",
      "brs.Constants",
      "org.json.simple.JSONObject",
      "brs.TransactionImpl",
      "org.bouncycastle.asn1.ASN1ObjectIdentifier",
      "org.bouncycastle.asn1.x509.X509ObjectIdentifiers",
      "org.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers",
      "org.bouncycastle.asn1.x509.X509Name",
      "brs.Account",
      "brs.util.Convert",
      "brs.BlockImpl"
    );
  }
}
